package pojo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TransMessageData.proto

public final class TransMessageData {
  private TransMessageData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MessageData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 magic = 1;</code>
     * @return The magic.
     */
    int getMagic();

    /**
     * <code>uint64 serial_num = 2;</code>
     * @return The serialNum.
     */
    long getSerialNum();

    /**
     * <code>uint32 session_id = 3;</code>
     * @return The sessionId.
     */
    int getSessionId();

    /**
     * <code>uint32 token = 4;</code>
     * @return The token.
     */
    int getToken();

    /**
     * <code>uint32 seq = 5;</code>
     * @return The seq.
     */
    int getSeq();

    /**
     * <code>.MessageData.DataType type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.MessageData.DataType type = 6;</code>
     * @return The type.
     */
    MessageData.DataType getType();

    /**
     * <code>int64 len = 7;</code>
     * @return The len.
     */
    long getLen();

    /**
     * <code>.MessageData.Content content = 8;</code>
     * @return Whether the content field is set.
     */
    boolean hasContent();
    /**
     * <code>.MessageData.Content content = 8;</code>
     * @return The content.
     */
    MessageData.Content getContent();
    /**
     * <code>.MessageData.Content content = 8;</code>
     */
    MessageData.ContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code MessageData}
   */
  public static final class MessageData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MessageData)
      MessageDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageData.newBuilder() to construct.
    private MessageData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageData() {
      type_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageData();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              magic_ = input.readUInt32();
              break;
            }
            case 16: {

              serialNum_ = input.readUInt64();
              break;
            }
            case 24: {

              sessionId_ = input.readUInt32();
              break;
            }
            case 32: {

              token_ = input.readUInt32();
              break;
            }
            case 40: {

              seq_ = input.readUInt32();
              break;
            }
            case 48: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 56: {

              len_ = input.readInt64();
              break;
            }
            case 66: {
              Content.Builder subBuilder = null;
              if (content_ != null) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(Content.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TransMessageData.internal_static_MessageData_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TransMessageData.internal_static_MessageData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageData.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MessageData.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *���ߵ�¼��֤���� �Ȼ�����Ϣ�ϱ�
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      REQ_LOGIN(0),
      /**
       * <pre>
       *�������ߵ�¼״̬�������Ϣ
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      RSP_LOGIN(1),
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      PING(2),
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      PONG(3),
      /**
       * <pre>
       *ע������
       * </pre>
       *
       * <code>REQ_REG = 4;</code>
       */
      REQ_REG(4),
      /**
       * <pre>
       *ע����Ӧ
       * </pre>
       *
       * <code>RSP_REG = 5;</code>
       */
      RSP_REG(5),
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>REQ_TRANS = 6;</code>
       */
      REQ_TRANS(6),
      /**
       * <pre>
       *������Ӧ
       * </pre>
       *
       * <code>RSP_TRANS = 7;</code>
       */
      RSP_TRANS(7),
      /**
       * <pre>
       *����״̬��
       * </pre>
       *
       * <code>RSP_ERROR = 8;</code>
       */
      RSP_ERROR(8),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *���ߵ�¼��֤���� �Ȼ�����Ϣ�ϱ�
       * </pre>
       *
       * <code>REQ_LOGIN = 0;</code>
       */
      public static final int REQ_LOGIN_VALUE = 0;
      /**
       * <pre>
       *�������ߵ�¼״̬�������Ϣ
       * </pre>
       *
       * <code>RSP_LOGIN = 1;</code>
       */
      public static final int RSP_LOGIN_VALUE = 1;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PING = 2;</code>
       */
      public static final int PING_VALUE = 2;
      /**
       * <pre>
       *����
       * </pre>
       *
       * <code>PONG = 3;</code>
       */
      public static final int PONG_VALUE = 3;
      /**
       * <pre>
       *ע������
       * </pre>
       *
       * <code>REQ_REG = 4;</code>
       */
      public static final int REQ_REG_VALUE = 4;
      /**
       * <pre>
       *ע����Ӧ
       * </pre>
       *
       * <code>RSP_REG = 5;</code>
       */
      public static final int RSP_REG_VALUE = 5;
      /**
       * <pre>
       *��������
       * </pre>
       *
       * <code>REQ_TRANS = 6;</code>
       */
      public static final int REQ_TRANS_VALUE = 6;
      /**
       * <pre>
       *������Ӧ
       * </pre>
       *
       * <code>RSP_TRANS = 7;</code>
       */
      public static final int RSP_TRANS_VALUE = 7;
      /**
       * <pre>
       *����״̬��
       * </pre>
       *
       * <code>RSP_ERROR = 8;</code>
       */
      public static final int RSP_ERROR_VALUE = 8;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return REQ_LOGIN;
          case 1: return RSP_LOGIN;
          case 2: return PING;
          case 3: return PONG;
          case 4: return REQ_REG;
          case 5: return RSP_REG;
          case 6: return REQ_TRANS;
          case 7: return RSP_TRANS;
          case 8: return RSP_ERROR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MessageData.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MessageData.DataType)
    }

    public interface ContentOrBuilder extends
        // @@protoc_insertion_point(interface_extends:MessageData.Content)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 contentLength = 1;</code>
       * @return The contentLength.
       */
      long getContentLength();

      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      com.google.protobuf.ByteString getData();
    }
    /**
     * Protobuf type {@code MessageData.Content}
     */
    public static final class Content extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:MessageData.Content)
        ContentOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Content.newBuilder() to construct.
      private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Content() {
        data_ = com.google.protobuf.ByteString.EMPTY;
      }

      @Override
      @SuppressWarnings({"unused"})
      protected Object newInstance(
          UnusedPrivateParameter unused) {
        return new Content();
      }

      @Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Content(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                contentLength_ = input.readInt64();
                break;
              }
              case 18: {

                data_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransMessageData.internal_static_MessageData_Content_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransMessageData.internal_static_MessageData_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Content.class, Builder.class);
      }

      public static final int CONTENTLENGTH_FIELD_NUMBER = 1;
      private long contentLength_;
      /**
       * <code>int64 contentLength = 1;</code>
       * @return The contentLength.
       */
      @Override
      public long getContentLength() {
        return contentLength_;
      }

      public static final int DATA_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString data_;
      /**
       * <code>bytes data = 2;</code>
       * @return The data.
       */
      @Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }

      private byte memoizedIsInitialized = -1;
      @Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (contentLength_ != 0L) {
          output.writeInt64(1, contentLength_);
        }
        if (!data_.isEmpty()) {
          output.writeBytes(2, data_);
        }
        unknownFields.writeTo(output);
      }

      @Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (contentLength_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, contentLength_);
        }
        if (!data_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, data_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @Override
      public boolean equals(final Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof Content)) {
          return super.equals(obj);
        }
        Content other = (Content) obj;

        if (getContentLength()
            != other.getContentLength()) return false;
        if (!getData()
            .equals(other.getData())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + CONTENTLENGTH_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getContentLength());
        hash = (37 * hash) + DATA_FIELD_NUMBER;
        hash = (53 * hash) + getData().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static Content parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static Content parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static Content parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Content parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static Content parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static Content parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static Content parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(Content prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @Override
      protected Builder newBuilderForType(
          BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code MessageData.Content}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:MessageData.Content)
          ContentOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return TransMessageData.internal_static_MessageData_Content_descriptor;
        }

        @Override
        protected FieldAccessorTable
            internalGetFieldAccessorTable() {
          return TransMessageData.internal_static_MessageData_Content_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  Content.class, Builder.class);
        }

        // Construct using TransMessageData.MessageData.Content.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @Override
        public Builder clear() {
          super.clear();
          contentLength_ = 0L;

          data_ = com.google.protobuf.ByteString.EMPTY;

          return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return TransMessageData.internal_static_MessageData_Content_descriptor;
        }

        @Override
        public Content getDefaultInstanceForType() {
          return Content.getDefaultInstance();
        }

        @Override
        public Content build() {
          Content result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @Override
        public Content buildPartial() {
          Content result = new Content(this);
          result.contentLength_ = contentLength_;
          result.data_ = data_;
          onBuilt();
          return result;
        }

        @Override
        public Builder clone() {
          return super.clone();
        }
        @Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.setField(field, value);
        }
        @Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return super.addRepeatedField(field, value);
        }
        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof Content) {
            return mergeFrom((Content)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(Content other) {
          if (other == Content.getDefaultInstance()) return this;
          if (other.getContentLength() != 0L) {
            setContentLength(other.getContentLength());
          }
          if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
            setData(other.getData());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @Override
        public final boolean isInitialized() {
          return true;
        }

        @Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Content parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (Content) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long contentLength_ ;
        /**
         * <code>int64 contentLength = 1;</code>
         * @return The contentLength.
         */
        @Override
        public long getContentLength() {
          return contentLength_;
        }
        /**
         * <code>int64 contentLength = 1;</code>
         * @param value The contentLength to set.
         * @return This builder for chaining.
         */
        public Builder setContentLength(long value) {
          
          contentLength_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 contentLength = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearContentLength() {
          
          contentLength_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>bytes data = 2;</code>
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
          return data_;
        }
        /**
         * <code>bytes data = 2;</code>
         * @param value The data to set.
         * @return This builder for chaining.
         */
        public Builder setData(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          data_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>bytes data = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearData() {
          
          data_ = getDefaultInstance().getData();
          onChanged();
          return this;
        }
        @Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:MessageData.Content)
      }

      // @@protoc_insertion_point(class_scope:MessageData.Content)
      private static final Content DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Content();
      }

      public static Content getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Content>
          PARSER = new com.google.protobuf.AbstractParser<Content>() {
        @Override
        public Content parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Content(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Content> parser() {
        return PARSER;
      }

      @Override
      public com.google.protobuf.Parser<Content> getParserForType() {
        return PARSER;
      }

      @Override
      public Content getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int MAGIC_FIELD_NUMBER = 1;
    private int magic_;
    /**
     * <code>uint32 magic = 1;</code>
     * @return The magic.
     */
    @Override
    public int getMagic() {
      return magic_;
    }

    public static final int SERIAL_NUM_FIELD_NUMBER = 2;
    private long serialNum_;
    /**
     * <code>uint64 serial_num = 2;</code>
     * @return The serialNum.
     */
    @Override
    public long getSerialNum() {
      return serialNum_;
    }

    public static final int SESSION_ID_FIELD_NUMBER = 3;
    private int sessionId_;
    /**
     * <code>uint32 session_id = 3;</code>
     * @return The sessionId.
     */
    @Override
    public int getSessionId() {
      return sessionId_;
    }

    public static final int TOKEN_FIELD_NUMBER = 4;
    private int token_;
    /**
     * <code>uint32 token = 4;</code>
     * @return The token.
     */
    @Override
    public int getToken() {
      return token_;
    }

    public static final int SEQ_FIELD_NUMBER = 5;
    private int seq_;
    /**
     * <code>uint32 seq = 5;</code>
     * @return The seq.
     */
    @Override
    public int getSeq() {
      return seq_;
    }

    public static final int TYPE_FIELD_NUMBER = 6;
    private int type_;
    /**
     * <code>.MessageData.DataType type = 6;</code>
     * @return The enum numeric value on the wire for type.
     */
    @Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.MessageData.DataType type = 6;</code>
     * @return The type.
     */
    @Override public DataType getType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(type_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int LEN_FIELD_NUMBER = 7;
    private long len_;
    /**
     * <code>int64 len = 7;</code>
     * @return The len.
     */
    @Override
    public long getLen() {
      return len_;
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private Content content_;
    /**
     * <code>.MessageData.Content content = 8;</code>
     * @return Whether the content field is set.
     */
    @Override
    public boolean hasContent() {
      return content_ != null;
    }
    /**
     * <code>.MessageData.Content content = 8;</code>
     * @return The content.
     */
    @Override
    public Content getContent() {
      return content_ == null ? Content.getDefaultInstance() : content_;
    }
    /**
     * <code>.MessageData.Content content = 8;</code>
     */
    @Override
    public ContentOrBuilder getContentOrBuilder() {
      return getContent();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (magic_ != 0) {
        output.writeUInt32(1, magic_);
      }
      if (serialNum_ != 0L) {
        output.writeUInt64(2, serialNum_);
      }
      if (sessionId_ != 0) {
        output.writeUInt32(3, sessionId_);
      }
      if (token_ != 0) {
        output.writeUInt32(4, token_);
      }
      if (seq_ != 0) {
        output.writeUInt32(5, seq_);
      }
      if (type_ != DataType.REQ_LOGIN.getNumber()) {
        output.writeEnum(6, type_);
      }
      if (len_ != 0L) {
        output.writeInt64(7, len_);
      }
      if (content_ != null) {
        output.writeMessage(8, getContent());
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (magic_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, magic_);
      }
      if (serialNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, serialNum_);
      }
      if (sessionId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, sessionId_);
      }
      if (token_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, token_);
      }
      if (seq_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, seq_);
      }
      if (type_ != DataType.REQ_LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, type_);
      }
      if (len_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, len_);
      }
      if (content_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getContent());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MessageData)) {
        return super.equals(obj);
      }
      MessageData other = (MessageData) obj;

      if (getMagic()
          != other.getMagic()) return false;
      if (getSerialNum()
          != other.getSerialNum()) return false;
      if (getSessionId()
          != other.getSessionId()) return false;
      if (getToken()
          != other.getToken()) return false;
      if (getSeq()
          != other.getSeq()) return false;
      if (type_ != other.type_) return false;
      if (getLen()
          != other.getLen()) return false;
      if (hasContent() != other.hasContent()) return false;
      if (hasContent()) {
        if (!getContent()
            .equals(other.getContent())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAGIC_FIELD_NUMBER;
      hash = (53 * hash) + getMagic();
      hash = (37 * hash) + SERIAL_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSerialNum());
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken();
      hash = (37 * hash) + SEQ_FIELD_NUMBER;
      hash = (53 * hash) + getSeq();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + LEN_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLen());
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MessageData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MessageData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MessageData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MessageData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MessageData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MessageData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MessageData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MessageData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MessageData)
        MessageDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TransMessageData.internal_static_MessageData_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TransMessageData.internal_static_MessageData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MessageData.class, Builder.class);
      }

      // Construct using TransMessageData.MessageData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        magic_ = 0;

        serialNum_ = 0L;

        sessionId_ = 0;

        token_ = 0;

        seq_ = 0;

        type_ = 0;

        len_ = 0L;

        if (contentBuilder_ == null) {
          content_ = null;
        } else {
          content_ = null;
          contentBuilder_ = null;
        }
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TransMessageData.internal_static_MessageData_descriptor;
      }

      @Override
      public MessageData getDefaultInstanceForType() {
        return MessageData.getDefaultInstance();
      }

      @Override
      public MessageData build() {
        MessageData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MessageData buildPartial() {
        MessageData result = new MessageData(this);
        result.magic_ = magic_;
        result.serialNum_ = serialNum_;
        result.sessionId_ = sessionId_;
        result.token_ = token_;
        result.seq_ = seq_;
        result.type_ = type_;
        result.len_ = len_;
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MessageData) {
          return mergeFrom((MessageData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MessageData other) {
        if (other == MessageData.getDefaultInstance()) return this;
        if (other.getMagic() != 0) {
          setMagic(other.getMagic());
        }
        if (other.getSerialNum() != 0L) {
          setSerialNum(other.getSerialNum());
        }
        if (other.getSessionId() != 0) {
          setSessionId(other.getSessionId());
        }
        if (other.getToken() != 0) {
          setToken(other.getToken());
        }
        if (other.getSeq() != 0) {
          setSeq(other.getSeq());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getLen() != 0L) {
          setLen(other.getLen());
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MessageData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MessageData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int magic_ ;
      /**
       * <code>uint32 magic = 1;</code>
       * @return The magic.
       */
      @Override
      public int getMagic() {
        return magic_;
      }
      /**
       * <code>uint32 magic = 1;</code>
       * @param value The magic to set.
       * @return This builder for chaining.
       */
      public Builder setMagic(int value) {
        
        magic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 magic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagic() {
        
        magic_ = 0;
        onChanged();
        return this;
      }

      private long serialNum_ ;
      /**
       * <code>uint64 serial_num = 2;</code>
       * @return The serialNum.
       */
      @Override
      public long getSerialNum() {
        return serialNum_;
      }
      /**
       * <code>uint64 serial_num = 2;</code>
       * @param value The serialNum to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNum(long value) {
        
        serialNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 serial_num = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSerialNum() {
        
        serialNum_ = 0L;
        onChanged();
        return this;
      }

      private int sessionId_ ;
      /**
       * <code>uint32 session_id = 3;</code>
       * @return The sessionId.
       */
      @Override
      public int getSessionId() {
        return sessionId_;
      }
      /**
       * <code>uint32 session_id = 3;</code>
       * @param value The sessionId to set.
       * @return This builder for chaining.
       */
      public Builder setSessionId(int value) {
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 session_id = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSessionId() {
        
        sessionId_ = 0;
        onChanged();
        return this;
      }

      private int token_ ;
      /**
       * <code>uint32 token = 4;</code>
       * @return The token.
       */
      @Override
      public int getToken() {
        return token_;
      }
      /**
       * <code>uint32 token = 4;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(int value) {
        
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 token = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        
        token_ = 0;
        onChanged();
        return this;
      }

      private int seq_ ;
      /**
       * <code>uint32 seq = 5;</code>
       * @return The seq.
       */
      @Override
      public int getSeq() {
        return seq_;
      }
      /**
       * <code>uint32 seq = 5;</code>
       * @param value The seq to set.
       * @return This builder for chaining.
       */
      public Builder setSeq(int value) {
        
        seq_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 seq = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSeq() {
        
        seq_ = 0;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.MessageData.DataType type = 6;</code>
       * @return The enum numeric value on the wire for type.
       */
      @Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.MessageData.DataType type = 6;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MessageData.DataType type = 6;</code>
       * @return The type.
       */
      @Override
      public DataType getType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(type_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.MessageData.DataType type = 6;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MessageData.DataType type = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private long len_ ;
      /**
       * <code>int64 len = 7;</code>
       * @return The len.
       */
      @Override
      public long getLen() {
        return len_;
      }
      /**
       * <code>int64 len = 7;</code>
       * @param value The len to set.
       * @return This builder for chaining.
       */
      public Builder setLen(long value) {
        
        len_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 len = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLen() {
        
        len_ = 0L;
        onChanged();
        return this;
      }

      private Content content_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Content, Content.Builder, ContentOrBuilder> contentBuilder_;
      /**
       * <code>.MessageData.Content content = 8;</code>
       * @return Whether the content field is set.
       */
      public boolean hasContent() {
        return contentBuilder_ != null || content_ != null;
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       * @return The content.
       */
      public Content getContent() {
        if (contentBuilder_ == null) {
          return content_ == null ? Content.getDefaultInstance() : content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public Builder setContent(Content value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public Builder setContent(
          Content.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public Builder mergeContent(Content value) {
        if (contentBuilder_ == null) {
          if (content_ != null) {
            content_ =
              Content.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = null;
          onChanged();
        } else {
          content_ = null;
          contentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public Content.Builder getContentBuilder() {
        
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      public ContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_ == null ?
              Content.getDefaultInstance() : content_;
        }
      }
      /**
       * <code>.MessageData.Content content = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Content, Content.Builder, ContentOrBuilder>
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Content, Content.Builder, ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MessageData)
    }

    // @@protoc_insertion_point(class_scope:MessageData)
    private static final MessageData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MessageData();
    }

    public static MessageData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageData>
        PARSER = new com.google.protobuf.AbstractParser<MessageData>() {
      @Override
      public MessageData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageData> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MessageData> getParserForType() {
      return PARSER;
    }

    @Override
    public MessageData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageData_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MessageData_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026TransMessageData.proto\"\357\002\n\013MessageData" +
      "\022\r\n\005magic\030\001 \001(\r\022\022\n\nserial_num\030\002 \001(\004\022\022\n\ns" +
      "ession_id\030\003 \001(\r\022\r\n\005token\030\004 \001(\r\022\013\n\003seq\030\005 " +
      "\001(\r\022#\n\004type\030\006 \001(\0162\025.MessageData.DataType" +
      "\022\013\n\003len\030\007 \001(\003\022%\n\007content\030\010 \001(\0132\024.Message" +
      "Data.Content\032.\n\007Content\022\025\n\rcontentLength" +
      "\030\001 \001(\003\022\014\n\004data\030\002 \001(\014\"\203\001\n\010DataType\022\r\n\tREQ" +
      "_LOGIN\020\000\022\r\n\tRSP_LOGIN\020\001\022\010\n\004PING\020\002\022\010\n\004PON" +
      "G\020\003\022\013\n\007REQ_REG\020\004\022\013\n\007RSP_REG\020\005\022\r\n\tREQ_TRA" +
      "NS\020\006\022\r\n\tRSP_TRANS\020\007\022\r\n\tRSP_ERROR\020\010B\022B\020Tr" +
      "ansMessageDatab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MessageData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MessageData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageData_descriptor,
        new String[] { "Magic", "SerialNum", "SessionId", "Token", "Seq", "Type", "Len", "Content", });
    internal_static_MessageData_Content_descriptor =
      internal_static_MessageData_descriptor.getNestedTypes().get(0);
    internal_static_MessageData_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MessageData_Content_descriptor,
        new String[] { "ContentLength", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
